spring:
  datasource:
    username: root
    password: 数据库密码
    url: jdbc:mysql://localhost:13306/dousheng
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    restart:
      enabled: true

  resources:
    static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:/resource/com/douSheng/mapper/*.xml
  type-aliases-package: com.douSheng.mapper
server:
  port: 8081

